### ISSUE TITLE
highlights are not removed after deleting the problematic code

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#463] opened 2021-11-03 21:12 UTC
![image](https://user-images.githubusercontent.com/57059538/140193489-f3927b18-0870-4bfb-9210-83aed442bbf7.png)

these highlights are placed using `addHighlightToConstruct()` in the `getCodeStatus()` function

**Comment by vicchig** [comment] 2021-11-05 19:46
This is weird. I fixed this one before, looks like the fix was undone somewhere accidentally. 

This is caused by the same issue as #330, in fact they are exactly the same bug. 
This commit fixes it: 257be18

It seems this commit was then undone in: d499ab

I don't know why it was changed back, maybe it was committed out of order and git overwrote it with the remote's version or some weird merge happened somewhere.

**Closed** 2021-11-06 15:57 UTC
Labels: bug
